# Generated by Django 5.0.14 on 2025-11-09 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('y1', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='x1',
        ),
    ]
