# Generated by Django 5.2.6 on 2025-11-12 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration_login_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='x1',
        ),
    ]
